apiVersion: v1
kind: Service
metadata:
  name: {{.Values.apiserverName}}
  namespace: {{.Values.namespace.name}}
  labels:
    app: federated-cluster
spec:
  type: LoadBalancer
  selector:
    app: federated-cluster
    module: federation-apiserver
  ports:
    - name: https
      protocol: TCP
      port: 443
      targetPort: 443
