apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: {{.controllerManager.name}}
  namespace: {{.namespace}}
  labels:
    app: federated-cluster
spec:
  template:
    metadata:
      name: federation-controller-manager
      labels:
        app: federated-cluster
        module: federation-controller-manager
    spec:
      volumes:
      - name: ssl-certs
        hostPath:
          path: /etc/ssl/certs
      containers:
      - name: controller-manager
        volumeMounts:
        - name: ssl-certs
          readOnly: true
          mountPath: /etc/ssl/certs
        image: {{.controllerManager.image}}:{{.controllerManager.imageTag}}
        command:
        - /usr/local/bin/federation-controller-manager
        - --master=https://{{.apiserver.name}}
        - --dns-provider={{.dnsProvider}}
        - --dns-provider-config={{.dnsProviderConfig}}
        - --federation-name={{.federationName}}
        - --zone-name={{.dnsZone}}
        ports:
        - containerPort: 443
          name: https
        - containerPort: 8080
          name: local
        env:
        - name: POD_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
