apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: {{.Values.controllerManagerName}}
  namespace: {{.Values.namespace}}
  labels:
    app: federated-cluster
spec:
  template:
    metadata:
      name: federation-controller-manager
      labels:
        app: federated-cluster
        module: federation-controller-manager
    spec:
      volumes:
      - name: kubeconfig
        secret:
          secretName: {{.Values.controllerManagerName}}-kubeconfig
      containers:
      - name: controller-manager
        volumeMounts:
        - name: kubeconfig
          readOnly: true
          mountPath: "/etc/federation/controller-manager",
        image: {{.Values.controllerManagerRegistry}}/hyperkube-amd64:{{.Values.controllerManagerVersion}}
        command:
        - /hyperkube
        - federation-controller-manager
        - --master=https://{{.Values.apiserverName}}
        - --kubeconfig=/etc/federation/controller-manager/kubeconfig
        - --dns-provider={{.Values.controllerManagerDNSProvider}}
        - --dns-provider-config={{.Values.controllerManagerDNSProviderConfig}}
        - --federation-name={{.Values.controllerManagerFederationName}}
        - --zone-name={{.Values.controllerManagerDNSZone}}
        ports:
        - containerPort: 443
          name: https
        - containerPort: 8080
          name: local
        env:
        - name: POD_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
