apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{.apiserver.name}}-etcd-claim
  annotations:
    volume.alpha.kubernetes.io/storage-class: "yes"
  namespace: {{.namespace}}
  labels:
    app: federated-cluster
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
