apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{.Values.apiserverName}}-etcd-claim
  annotations:
    volume.alpha.kubernetes.io/storage-class: "yes"
    "helm.sh/hook": pre-install
  namespace: {{.Values.namespace}}
  labels:
    app: federated-cluster
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
