apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: federation-controller-manager
  namespace: federation
  labels:
    app: federated-cluster
spec:
  template:
    metadata:
      name: federation-controller-manager
      labels:
        app: federated-cluster
        module: federation-controller-manager
    spec:
      volumes:
      - name: ssl-certs
        hostPath:
          path: /etc/ssl/certs
      containers:
      - name: controller-manager
        volumeMounts:
        - name: ssl-certs
          readOnly: true
          mountPath: /etc/ssl/certs
        image: gcr.io/madhusudancs-k8s/federation-controller-manager:v1.4.0-alpha.0.892_cd9deccbbf9b08-dirty
        command:
        - /usr/local/bin/federation-controller-manager
        - --master=https://federation-apiserver:443
        - --dns-provider=google-clouddns
        - --dns-provider-config=
        - --federation-name=myfederation
        - --zone-name=ubernetes-test.com
        ports:
        - containerPort: 443
          name: https
        - containerPort: 8080
          name: local
        env:
        - name: POD_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
