#! /bin/bash

set -o errexit
set -o pipefail
set -o nounset
set -x

cd "${BASH_SOURCE%/*}"

gen() {
  mkdir -p .gen/
  jsonnet -J ../ --multi .gen/ all.jsonnet
}

deploy() {
  gen
  terraform apply .gen
}

destroy() {
  terraform destroy .gen
}

case "${1:-}" in
  "")
    ;;
  "deploy")
    deploy
    ;;
  "destroy")
    destroy
    ;;
  "gen")
    gen
    ;;
esac
